#include <Arduino.h>

#include "configuration.h"
#include <KMegaService.h>

/* REMINDER: 
When programming KMega, set:
	1. File > Preferences > Sketchbook location = C:\dev\KCP2\KMega
	2. Tools > Board = Arduino Mega or Mega 2560
	3. Tools > Processor = ATmega2560 (Mega 2560)
	4. Tools > Port = COM4
*/

KMegaService * kMegaServicePointer = NULL;
int tempCounter1 = 0;
int tempCounter2 = 0;
long time1 = 0;
long time2 = 0;
long time3 = 0;
long max_time = 0;

void setup() {
	KMegaService kMegaService;
	kMegaServicePointer = &kMegaService;
	
	/*
	Interrupts are enabled by default.
	All timers depend on the system clock of your Arduino system. Normally the system clock is 16MHz.
	
	The Arduino Mega has 6 timers:
	timer0:  8 bit timer. Used for the timer functions like delay(), millis(), micros(), etc.
	timer1: 16 bit timer.
	timer2:  8 bit timer.
	timer3: 16 bit timer.
	timer4: 16 bit timer.
	timer5: 16 bit timer. Used by Servo library.
	*/
	// >>> The following code is generated by the Arduino Timer Interrupts Calculator:
	//http://www.8bit-era.cz/arduino-timer-interrupts-calculator.html
	// TIMER 1 for interrupt frequency 4000 Hz:
	cli(); // stop interrupts
	TCCR1A = 0; // set entire TCCR1A register to 0
	TCCR1B = 0; // same for TCCR1B
	TCNT1  = 0; // initialize counter value to 0
	// set compare match register for 4000 Hz increments
	OCR1A = 3999; // = 16000000 / (1 * 4000) - 1 (must be <65536)
	// turn on CTC mode
	TCCR1B |= (1 << WGM12);
	// Set CS12, CS11 and CS10 bits for 1 prescaler
	TCCR1B |= (0 << CS12) | (0 << CS11) | (1 << CS10);
	// enable timer compare interrupt
	TIMSK1 |= (1 << OCIE1A);
	sei(); // allow interrupts
	// <<< The prior code was generated by the Arduino Timer Interrupts Calculator (see link above)
	
	kMegaService.run();
	
	//static const int SERIAL_READ_TIMEOUT_IN_MILLISECONDS = 10000;
	//static const unsigned long COMPUTER_BAUD_RATE = 115200;
	//Serial.setTimeout(SERIAL_READ_TIMEOUT_IN_MILLISECONDS);
	//Serial.begin(COMPUTER_BAUD_RATE);
	//
	//long someLong = 1234;
	//char cstring[16];
	//ltoa(someLong, cstring, 10);
	//delay(3000);
	//Serial.println("garbage");
	//Serial.print(cstring);
	
}

ISR (TIMER1_COMPA_vect) {
	//tempCounter1++;
	//tempCounter2++;
	
	//if(tempCounter1 == 100) {
		//time1 = millis();
	//}
	
	if(kMegaServicePointer != NULL) {
		kMegaServicePointer->controlPanel.runStepperIfNecessary();
	}
	
	//if(tempCounter1 == 100) {
	//	time2 = millis();
	//	time3 = time2 - time1;
	//	if (time3 > max_time) {
	//		max_time = time3;
	//	}
	//	//tempCounter1 = 0;
	//}
	
	//if(tempCounter2 == 5000) {
	//	kMegaServicePointer->serialCommunicator.sendKKIMTerminalDisplayPacket(max_time);
	//	tempCounter2 = 0;
	//}
}

void loop() {
}












