/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Kerbal.Kontroller.Interface.Module;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
