/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mountaineerman.kcp2.kkim.app;

import mountaineerman.kcp2.kkim.list.LinkedList;

import static mountaineerman.kcp2.kkim.utilities.StringUtils.join;
import static mountaineerman.kcp2.kkim.utilities.StringUtils.split;
import static mountaineerman.kcp2.kkim.app.MessageUtils.getMessage;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        System.out.println(join(tokens));
    }
}
